x-common: &common
  environment:
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
    GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp-credentials
    TF_CPP_MIN_LOG_LEVEL: '3'
  volumes:
    - ${PWD}/shared_with_container:/app/shared_with_container
  secrets:
    - gcp-credentials

x-gpu: &gpu
  <<: *common
  runtime: nvidia

services:
  hailo:
    <<: *gpu
    image: "luxonis/modelconverter-hailo:latest"
    entrypoint: /app/entrypoint.sh

  rvc2:
    <<: *common
    image: "luxonis/modelconverter-rvc2:latest"
    entrypoint: /app/entrypoint.sh

  rvc3:
    <<: *common
    image: "luxonis/modelconverter-rvc3:latest"
    entrypoint: /app/entrypoint.sh

  rvc4:
    <<: *common
    image: "luxonis/modelconverter-rvc4:latest"
    entrypoint: /app/entrypoint.sh

secrets:
  gcp-credentials:
    file: ${GOOGLE_APPLICATION_CREDENTIALS}
