input_model: "s3://luxonis-test-bucket/modelconverter-test/yolov6n.onnx"

mean_values: [ 0, 0, 0 ]
scale_values: [ 255, 255, 255 ]
keep_intermediate_outputs: true

calibration:
  path: "s3://luxonis-test-bucket/modelconverter-test/imagenette-calib.zip"
  max_images: 20

inputs:
  - name: images
    shape: [ 1, 3, 416, 416 ]
    layout: NCHW

outputs:
  - name: output1_yolov6r2
    layout: NCHW
  - name: output2_yolov6r2
    layout: NCHW
  - name: output3_yolov6r2
    layout: NCHW
