#!/bin/bash

source $(find /opt/intel -name setupvars.sh) -pyver 3.8 > /dev/null

COMPILE_TOOL=$(find /opt/intel -name compile_tool -type f)

if [[ "${VERSION}" = "2021.4.0" ]]; then
    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/lib/python3.8/site-packages/openvino/libs/"
fi

exec "${COMPILE_TOOL}" "${@}"
