#!/bin/bash

source $(find /opt/intel -name setupvars.sh) -pyver 3.8 > /dev/null

COMPILE_TOOL=$(find /opt/intel -name compile_tool -type f)

if [[ "${VERSION}" = "2021.4.0" ]]; then
    export LD_LIBRARY_PATH="/opt/intel/deployment_tools/inference_engine/:${LD_LIBRARY_PATH}"
fi

exec "${COMPILE_TOOL}" "${@}"
