#!/bin/bash

source $(find /opt/intel -name setupvars.sh) -pyver 3.8 > /dev/null

if [[ "${VERSION}" = "2021.4.0" ]]; then

    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/lib/python3.8/site-packages/openvino/libs/"

    # Yes, the `mo` command runs as a side effect of this import...
    exec python3.8 -c 'from mo import __main__' "${@}"
else
    exec python3.8 -c 'from openvino.tools.mo.__main__ import main' "${@}"
fi
