#!/usr/bin/env bash

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

# Keep the lockfile and the pip compatibility exports in sync with pyproject.toml.
uv lock

# The Docker image builds read the exports with plain pip. Keep them unhashed:
# each image installs its platform pins on top, and hash mode rejects a package
# that the same file does not pin.
#
# `opencv-python-headless` is overridden to an unsatisfiable marker in
# pyproject.toml, so it never installs. Do not emit the dead entry.
export_requirements() {
  local output="$1"
  shift

  local tmp
  tmp="$(mktemp "${output}.XXXXXX")"

  if ! {
    printf '%s\n' '# This file is autogenerated by uv. Do not edit it manually.'
    printf '%s\n' '# Add or update dependencies in pyproject.toml, then run tools/export_requirements.sh.'
    uv export --locked --format requirements.txt --no-header \
      --no-annotate --no-emit-project --no-hashes \
      --no-emit-package opencv-python-headless "$@"
  } >"$tmp"; then
    rm -f "$tmp"
    return 1
  fi

  mv "$tmp" "$output"
}

export_requirements requirements.txt --no-default-groups
export_requirements requirements-dev.txt --no-default-groups --group dev
