#!/usr/bin/env bash

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

# Keep the lockfile and the pip compatibility exports in sync with pyproject.toml.
uv lock

export_requirements() {
  local output="$1"
  shift

  local tmp
  tmp="$(mktemp "${output}.XXXXXX")"

  if ! {
    printf '%s\n' '# This file is autogenerated by uv. Do not edit it manually.'
    printf '%s\n' '# Add or update dependencies in pyproject.toml, then run tools/export_requirements.sh.'
    # The image builds install these exports, and `modelconv` itself is
    # installed from the source tree with `pip install -e . --no-deps`.
    #
    # `opencv-python-headless` is overridden to a marker that never matches, so
    # it never installs; skip emitting the dead entry. The exports stay
    # unhashed because of it: pip restores the package as an albumentations
    # dependency, and hash mode rejects a package the file does not list.
    uv export --locked --format requirements.txt --no-header \
      --no-annotate --no-emit-project --no-hashes \
      --no-emit-package opencv-python-headless "$@"
  } >"$tmp"; then
    rm -f "$tmp"
    return 1
  fi

  mv "$tmp" "$output"
}

export_requirements requirements.txt --no-default-groups

# Only the image builds read the development export, and each image pins the
# versions its vendor tools were built against: NumPy 1 for SNPE, protobuf
# 3.20.3 for the Hailo SDK, NumPy 1.23.4 for OpenVINO 2022.3. Emitting what the
# root lockfile resolves would undo those pins, because this export installs
# after the platform requirements. Leave them to pip, which keeps what the
# image already holds.
export_requirements requirements-dev.txt --only-group dev \
  --no-emit-package ml-dtypes \
  --no-emit-package numpy \
  --no-emit-package onnx \
  --no-emit-package protobuf
