#!/usr/bin/env bash

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

# One lockfile per environment: the root project for the host and CI, and one
# project per platform image. Each image installs the export of its own lock,
# so a build never resolves anything.
PLATFORMS=(rvc2 rvc3 rvc4 hailo)

export_requirements() {
  local project="$1"
  local output="$2"
  shift 2

  local tmp
  tmp="$(mktemp "${output}.XXXXXX")"

  if ! {
    printf '%s\n' '# This file is autogenerated by uv. Do not edit it manually.'
    printf '%s\n' '# Add or update dependencies in pyproject.toml, then run tools/export_requirements.sh.'
    # `modelconv` itself is installed from the source tree with `--no-deps`,
    # and `opencv-python-headless` is overridden to a marker that never
    # matches. Do not emit either.
    # Hashes stay in, and the image builds install with `--require-hashes`.
    uv export --directory "$project" --locked --format requirements.txt \
      --no-header --no-annotate --no-emit-project \
      --no-emit-package modelconv \
      --no-emit-package opencv-python-headless "$@"
  } >"$tmp"; then
    rm -f "$tmp"
    return 1
  fi

  mv "$tmp" "$output"
}

uv lock
for platform in "${PLATFORMS[@]}"; do
  uv lock --directory "modelconverter/platforms/${platform}"
done

for platform in "${PLATFORMS[@]}"; do
  dir="modelconverter/platforms/${platform}"
  export_requirements "$dir" "${dir}/requirements.txt"
  export_requirements "$dir" "${dir}/requirements-dev.txt" --extra test
done
