name: Export pydoctor reference

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  export:
    uses: luxonis/luxonis-ml/.github/workflows/reusable-export-pydoctor-reference.yaml@90b4157a4040727fe38905acecb02d75f2f9d768
    with:
      package-id: modelconverter
    secrets:
      DOCS_CONTENT_SSH_KEY: ${{ secrets.DOCS_CONTENT_SSH_KEY }}
