name: Test - HAILO

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - 'modelconverter/packages/hailo/**'
      - 'modelconverter/packages/base_exporter.py'
      - 'modelconverter/packages/base_inferer.py'
      - 'tests/test_packages/test_hailo.py'
      - 'docker/hailo/Dockerfile'
      - 'docker/hailo/entrypoint.sh'
      - '.github/workflows/modelconverter_test.yaml'
      - '.github/workflows/hailo_test.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hailo-test:

    strategy:
      fail-fast: false
      matrix:
        version: ["2025.01", "2025.04"]

    uses: ./.github/workflows/modelconverter_test.yaml
    secrets: inherit
    with:
      package: hailo
      version: ${{ matrix.version }}
      os: ubuntu-22.04-4core
