name: Release Tag

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: read

jobs:
  release:
    if: >-
      github.event.pull_request.merged &&
      startsWith(github.event.pull_request.head.ref, 'release/')
    uses: luxonis/luxonis-ml/.github/workflows/reusable-release-tag.yaml@90b4157a4040727fe38905acecb02d75f2f9d768
    with:
      version-file: modelconverter/__init__.py
    secrets:
      WORKFLOW_SECRET: ${{ secrets.WORKFLOW_SECRET }}
