name: Release Tag

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release:
    if: >-
      github.event.pull_request.merged &&
      startsWith(github.event.pull_request.head.ref, 'release/')
    uses: luxonis/luxonis-ml/.github/workflows/reusable-release-tag.yaml@59ca6fe93e5c854289dba1e4dede0700ee57d658
    with:
      version-file: modelconverter/__init__.py
    secrets:
      WORKFLOW_SECRET: ${{ secrets.WORKFLOW_SECRET }}
