name: Test - RVC2

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - main
    paths:
      - 'modelconverter/packages/rvc2/**'
      - 'modelconverter/packages/base_exporter.py'
      - 'modelconverter/packages/base_inferer.py'
      - 'tests/test_packages/test_rvc2.py'
      - 'docker/rvc2/Dockerfile'
      - 'docker/rvc2/entrypoint.sh'
      - '.github/workflows/modelconverter_test.yaml'
      - '.github/workflows/rvc2_test.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rvc2-test:

    strategy:
      fail-fast: false
      matrix:
        version: ["2021.4.0", "2022.3.0"]

    uses: ./.github/workflows/modelconverter_test.yaml
    secrets: inherit
    with:
      package: rvc2
      version: ${{ matrix.version }}
