name: Test - RVC2

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - main
    paths:
      - 'modelconverter/packages/rvc2/**'
      - 'tests/test_packages/test_rvc2.py'
      - 'dockerfiles/Dockerfile.rvc2'
      - 'entrypoints/entrypoint_rvc2.sh'
      - '.github/workflows/modelconverter_test.yaml'
      - '.github/workflows/rvc2_test.yaml'

jobs:
  rvc2-test:

    strategy:
      fail-fast: false
      matrix:
        version: ["2021.4.0", "2022.3.0"]

    uses: ./.github/workflows/modelconverter_test.yaml
    secrets: inherit
    with:
      package: rvc2
      version: ${{ matrix.version }}
