name: Test - RVC3

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - 'modelconverter/packages/rvc3/**'
      - 'modelconverter/packages/base_exporter.py'
      - 'modelconverter/packages/base_inferer.py'
      - 'tests/test_packages/test_rvc3.py'
      - 'dockerfiles/Dockerfile.rvc3'
      - 'entrypoints/entrypoint_rvc3.sh'
      - '.github/workflows/modelconverter_test.yaml'
      - '.github/workflows/rvc3_test.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rvc3-test:
    uses: ./.github/workflows/modelconverter_test.yaml
    secrets: inherit
    with:
      package: rvc3
      version: "2022.3.0"
