name: Publish - RVC3

on:
  workflow_dispatch:

  release:
    types: [published]
    branches:
      - main

jobs:
  rvc3-publish:
    uses: ./.github/workflows/publish.yaml
    secrets: inherit
    with:
      package: rvc3
