name: Test - RVC4

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - main
    paths:
      - 'modelconverter/packages/rvc4/**'
      - 'modelconverter/packages/base_exporter.py'
      - 'modelconverter/packages/base_inferer.py'
      - 'tests/test_packages/test_rvc4.py'
      - 'dockerfiles/Dockerfile.rvc4'
      - 'entrypoints/entrypoint_rvc4.sh'
      - '.github/workflows/modelconverter_test.yaml'
      - '.github/workflows/rvc4_test.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rvc4-test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - "2.23.0"
          - "2.24.0"
          - "2.25.0"
          - "2.26.2"
          - "2.27.0"
          - "2.32.6"

    uses: ./.github/workflows/modelconverter_test.yaml
    secrets: inherit
    with:
      package: rvc4
      version: ${{ matrix.version }}
