name: Publish - RVC4

on:
  workflow_dispatch:

  release:
    types: [published]
    branches:
      - main

jobs:
  rvc4-publish:

    strategy:
      fail-fast: false
      matrix:
        version:
          - "2.23.0"
          - "2.24.0"
          - "2.25.0"
          - "2.26.2"
          - "2.27.0"
          - "2.32.6"

    uses: ./.github/workflows/publish.yaml
    secrets: inherit
    with:
      package: rvc4
      version: ${{ matrix.version }}
