name: Test - RVC4

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - main
    paths:
      - 'modelconverter/packages/rvc4/**'
      - 'tests/test_packages/test_rvc4.py'
      - 'dockerfiles/Dockerfile.rvc4'
      - 'entrypoints/entrypoint_rvc4.sh'
      - '.github/workflows/modelconverter_test.yaml'
      - '.github/workflows/rvc4_test.yaml'

jobs:
  rvc4-test:
    uses: ./.github/workflows/modelconverter_test.yaml
    secrets: inherit
    with:
      package: rvc4
