name: Unit Tests

on:
  pull_request:
    branches:
      - dev
      - main
    paths:
      - 'tests/test_utils/**'
      - 'modelconverter/**'
      - '.github/workflows/unittests.yaml'

  workflow_call:
    inputs:
      ml_ref:
        description: 'luxonis-ml version (branch/tag/SHA)'
        required: true
        type: string
      conv_ref:
        description: 'modelconverter version (branch/tag/SHA)'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  utils-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout at conv_ref (workflow_call)
      if: ${{ github.event_name == 'workflow_call' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.conv_ref }}

    - name: Checkout code
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        cache: pip

    - name: Install package
      run: python -m pip install -e .[dev] --extra-index-url https://artifacts.luxonis.com/artifactory/luxonis-python-release-local/

    - name: Install specified luxonis-ml
      if: ${{ github.event_name == 'workflow_call' }}
      run: |
        pip uninstall luxonis-ml -y || true
        pip install "luxonis-ml[all] @ git+https://github.com/luxonis/luxonis-ml.git@${{ inputs.ml_ref || steps.determine-refs.outputs.ml_ref }}" \
          --upgrade --force-reinstall

    - name: Run Unit Tests
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_ENDPOINT_URL: ${{ secrets.AWS_S3_ENDPOINT_URL }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        HUBAI_API_KEY: ${{ secrets.HUBAI_API_KEY }}
      run: python -m pytest tests/test_utils

